### PR TITLE
Fix crash on missing sound

### PR DESCRIPTION
**Pull request by Ferk**
The stone giant is causing the game to crash when killed without this change, because of the missing sound definition.

I fixed the crash but I left the missing sound in the stone_giant definition so this can be tested (it'll display an error). I guess the giant is WIP anyway.

### CODE REVIEW

**Comment by raymoo** [comment]
You better take your repository down (according to the readme), since the readme says you can't redistribute modified code with the artwork.

**Comment by Ferk** [comment]
The artwork is CC-BY-**ND**-4.0 ... I think the "implications" section might have gotten it wrong, it probably means that you can't redistribute the artwork while modifying it (the artwork, not the code). Otherwise it makes no sense to me.

But It would be nice to get a clarification from @sofar 
EDIT: [Just got one](https://forum.minetest.net/viewtopic.php?f=9&t=15572&p=234557#p234558)

**Comment by sofar** [comment]
@raymoo the code license doesn't apply to the artwork and vice versa.

https://creativecommons.org/licenses/by-nd/4.0/

Artwork is allowed to be redistributed, The creativecommons website paraphrases the ND clause as:

```
If you remix, transform, or build upon the material, you may not distribute the modified material. 
```

However, a github fork in my opinion is no `transform` and doesn't qualify as a `remix` or `build upon` either.

**Comment by sofar** [comment]
:+1: on the change, too

**Comment by raymoo** [comment]
@sofar The readme says that you cannot redistribute the artwork if you modify the code.

> 1) you can re-distribute the artwork, but only if you: a) properly attribute b) do not modify the code

Does "code" here refer to something other than the lua scripts?

**Comment by sofar** [comment]
@raymoo I'll fix that, that sentence is incorrect.

**Comment by sofar** [comment]
@raymoo So that paragraph basically was supposed to be about the artwork license, and it was supposed to say `you can re-distribute the artwork, but only if you: a) properly attribute b) do not modify the *artwork*[sic]`

Edit: Fixed the license text in the readme.

**Comment by raymoo** [comment]
Alright, thanks.

**Comment by Ferk** [comment]
Maybe this should be refactored and make a Driver.play_sound, there are several points in init.lua where it could be used as well i think

**Comment by sofar** [comment]
@ferk maybe, I feel it's a bit early for that, and would like to focus on other parts first.

**Pull request merged**
